config/routes.rb
Rails.application.routes.draw do
  resources :cities, only: [:show, :edit, :new, :create, :destroy, :update]
  resources :cities, :only => [:show,:index], :constraints => {:format => /(json|xml)/}
  resources :countries#, only: [:index, :new, :create, :destroy]
  get "listcountries" => redirect { |params, request| "/countries/?id=#{params[:id]}" }

  get 'listcities' => 'countries#list_cities'
  get 'cities', to: redirect('/countries')
  get 'upload' => 'countries#upload'

end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country
	mount_uploader :image, ImageCityUploader
	validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/country.rb
# require_relative '../uploaders/flag_uploader'
require 'carrierwave/orm/activerecord'
class Country < ActiveRecord::Base
	has_many :cities, -> { select 'cities.*' }
	mount_uploader :flag, FlagUploader 
	validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :error, :another_custom_type

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]


  def index
    @cities = City.paginate(:page => params[:page], :per_page => 10).order('name DESC')
  end


  def show
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
    @city = City.new(city_params)
    if !city_params[:image].nil? &&
      city_params[:image].original_filename == city_params[:url]
      @city.save
      @city.url = @city.image.url
    end
    respond_to do |format|
      if @city.save
        @country = Country.find_by(id: @city.country_id)
        format.html { redirect_to @country, success: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    p = city_params
    if !p[:image].nil?
      if p[:image].original_filename == city_params[:url]
        f = p[:image]
        p[:url] = File.join('/',imageUploader.dir,f.headers.split()[2].split(/\W+/)[1..-1],
          params[:id],f.original_filename)
      else
        p[:url] = city_params[:url]
      end
    else
      p[:url] = city_params[:url]
    end

    respond_to do |format|
      if @city.update(p)
        @country = Country.find_by(id: @city.country_id)
        format.html { redirect_to @country, success: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      @country = Country.find_by(id: @city.country_id)
      format.html { redirect_to @country, success: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_city
      @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(:country_id, :name, :image, :url)
    end

    # def city_text_params
    #   params.require(:city).permit(:country_id, :name, :url)
    # end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  
  def index
    @countries = Country.paginate(:page => params[:page], :per_page => 10).order('name DESC')
  end

  def list_cities
    """
    Get list cities of etraxt country by id
    """
    id = request.query_parameters[:id].to_i
    @data = Country.find(id).cities
    render json: @data.map { |d| {id: d.id,name: d.name,url: d.url}}
  end

  # def upload
  #   uploaded_io = params[:countries][:flag]
  #   File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  #     file.write(uploaded_io.read)
  #   end
  # end

  
  def show
    # @country = Country.find(params[:id])
    # byebug
  end

  def new
    @country = Country.new
  end

  def edit
  end

  
  def create
    @country = Country.new(country_params)
    if !country_params[:flag].nil? &&
      country_params[:flag].original_filename == country_params[:url]
      @country.save
      # path = @country.flag.store_path.split('/')
      # path.insert(3,@country.id)
      @country.url = @country.flag.url
    end
    # byebug
    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, success: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    """
    extract request data from client and assign
    """

    p = country_params
    if !p[:flag].nil?
      if p[:flag].original_filename == country_params[:url]
        f = p[:flag]
        p[:url] = File.join('/',FlagUploader.dir,f.headers.split()[2].split(/\W+/)[1..-1],
          params[:id],f.original_filename)
      else
        p[:url] = country_params[:url]
      end
    else
      p[:url] = country_params[:url]
    end
    # country_params[:url] = country_params[:flag].url
    respond_to do |format|
      if @country.update(p)
        format.html { redirect_to @country, success: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, success: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_country
      @country = Country.find(params[:id])
    end

    def country_params
      params.require(:country).permit(:name, :flag, :url)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper


	def image_tag(source, options={})
		source = "default.jpg" if source.blank? or source == nil
		super(source, options)
	end

	def bs_flash_class_for type
		# byebug
		case type.to_sym
			when :success 
				"alert-success"
			when :error 
				"alert-danger"
			when :notice 
				"alert-info"
			else 
				type.to_s
		end
  		# {
  		#  success: "alert-success",
  		#  error: "alert-danger",
  		#  notice: "alert-info"
  		# }[flash_type] || flash_type.to_s
  	end
  end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/cities/_form.html.erb
<script type="text/javascript">
  $(document).ready(function($) {
    $('input[type="file"]').on('change',function(){
      $('#city_url').val($('input[type="file"]').val());
    });
  });
</script>


<div class="containter">

<%= form_for @city, class: "form-group" do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <div class="row">
      <div class="col-xs-1">
        <%= f.label :country_id, class: "label" %>
      </div>
      <br>
      <div class="col-xs-6">
      <%= f.collection_select :country_id, Country.all, :id, :name , {prompt: "Select The Country"}, {class: "form-control"}%>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="row">
      <div class="col-xs-1">
        <%= f.label :name,class: "label" %><br>
      </div>
      <br>
      <div class="col-xs-6">
      <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="row">
      <div class="col-xs-1">
        <%= f.label :image, class: "label"  %> 
      </div>
      <br>
      <div class="col-xs-6">

      <div class="input-group">
        <span class="input-group-btn">
          <span class="btn btn-primary btn-file">
            Browse<%= f.file_field :image%>
          </span>
        </span>
        <%= f.text_field :url, class: "form-control"%>
      </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: "btn btn-info crud" %>
  </div>
<% end %>

</div>

app/views/cities/edit.html.erb
<div id="form" class="container">
<div class="panel panel-default">
<div class="panel-heading"><h1>Editing City</h1></div>
<div class="panel-body">
<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>
</div>
</div>
</div>
</div>

app/views/cities/new.html.erb
<div id="form" class="container">
<div class="panel panel-default">
<div class="panel-heading"><h1>New City</h1>
</div>
<div class="panel-body">


<%= render 'form' %>

<%= link_to 'Back', cities_path %>
</div>
</div>
</div>
</div>

app/views/cities/show.html.erb
<div class="well col-sm-12">
<div class="container">

<%= render partial: "shared/flash_messages", flash: flash %> 

<p>
  <strong>Countries:</strong>
  <%= @city.country_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @city.image %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>
</div>
</div>

app/views/countries/_form.html.erb
<script type="text/javascript">
  $(document).ready(function($) {
    $('input[type="file"]').on('change',function(){
      $('#country_url').val($('input[type="file"]').val());
    });
  });

</script>


<%= form_for @country, class: "form-group",html: { multipart: true } do |f| %>
<% if @country.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

  <ul>
    <% @country.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <div class="row">
    <div class="col-xs-1">
      <%= f.label :name, class: "label" %>
    </div>
    <br>

    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>
<div class="field">
  <div class="row">
    <div class="col-xs-1">
      <%= f.label :flag, class: "label"  %> 
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-btn">
        <span class="btn btn-primary btn-file">
          Browse<%= f.file_field :flag%>
        </span>
      </span>
      <%= f.text_field :url, class: "form-control"%>
    </div>
  </div>
</div>

<div class="actions">
  <%= f.submit 'Save',  class: "btn btn-primary crud"%>
</div>
<% end %>

app/views/countries/edit.html.erb
<div id="form" class="container">
<div class="panel panel-default">
<div class="panel-heading"><h1>Editing Country</h1>
</div>
<div class="panel-body">


<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>
</div>
</div>
</div>
</div>

app/views/countries/index.html.erb
<div class="container">

<!-- <% if !notice.nil? %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %> -->

<%= render partial: "shared/flash_messages", flash: flash %> 

<h1 style="float:left">Listing Countries</h1>
<p id="new"><%= link_to 'New Country', new_country_path, class: "btn btn-success" %></p>

<table class="table table-striped">
  <col width="33%">
  <col width="33%">
  <col width="33%">

  <thead>
    <tr>
      <th>Name</th>
      <th>Flag</th>
      <th colspan="3">CRUD</th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><a href="<%= country_path country.id%>"><%= country.name %></a></td>
        <td class="zoom-gallery">

        <!--<% img = '/uploads/default.jpg' %>
        <% if !country.flag.file.nil? %>
        <%    img = country.flag %>
        <% elsif country.url %>
        <%    img = country.url %>
        <% end %>
        -->


        <% img = '/uploads/default.jpg' %>
        <% if !country.url.nil? %>
        <%    img = country.url %>
        <% end %>
        
        <a href="<%= img %>">

        <img src="<%= img %>" width="100" height="50" crop="fill" class="zoom-gallery world" />
        <!--
        <%= image_tag img,:type => :upload, :width => 100, :height => 50, :crop => :fill, class: "zoom-gallery" %>-->
        </td>
        </a>
        <td>
        <%= link_to 'Edit', edit_country_path(country), class: "btn btn-success crud" %>
        <%= link_to 'Destroy', country,class: "btn btn btn-danger crud" , method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="digg_pagination text-center">
    <!-- <div class="page_info">
      <%= page_entries_info @countries %>
    </div> -->
    <%= will_paginate @countries, :container => false %>
  </div>
</div>

app/views/countries/new.html.erb
<div id="form" class="container">
<div class="panel panel-default">
<div class="panel-heading"><h1>New Country</h1></div>

<div class="panel-body"> 
<%= render 'form' %>



<%= link_to 'Back', countries_path %>
</div>
</div>
</div>
</div>

app/views/countries/show.html.erb
<script type="text/javascript">
	
	$(document).ready(function(){
		

		$('select#city').prepend(new Option(
			'Please select City','*'
		));

		$('select#city').val('*');
		var nameCountry = $('#nameCountry').text();
		$('select#country option').map(function(i, e) { 
			if($(e).text() === nameCountry){
				$('select#country').val(e.value);
				return true;
			}
			return false;
		});

		$('select#country').change(function(){
			var country_id = $('select#country').val();
			$('#nameCountry').text($('select#country option:selected').text());
			if(country_id != 0)
			{
				$.ajax({
					type:'get',
					url:'/listcities/',
					data:{id:country_id},
					cache:false,
					success: function(returndata){
						console.log(returndata);
						var options = '<option value="*">Please select City</option>';
						returndata.forEach(function(data){
							options += sprintf(
								"<option value='%s'>%s</option>",data.id,data.name
								);
	                    });
						$('select#city').html(options);
					}
				});
			}
		});

		$('select#city').change(function(){
			var city_id = $('select#city').val();
			if(city_id != 0)
			{
				$.ajax({
					type:'get',
					url:'/cities/'+city_id+'.json',
					data:{id:city_id},
					cache:false,
					success: function(returndata){
						var img = returndata.url === null ? '/uploads/default.jpg' : returndata.url;
						var dict = {};
						dict['div#image_cities'] = sprintf(
							"<a href='%s'><image id='img' src='%s'></image></a>",img, img );

						dict['div#edit'] = '<%= link_to "Edit", edit_city_path(1), class: "btn btn-info crud"%>'.replace('1',city_id);

						dict['div#destroy'] = '<%= link_to "Destroy", city_path(id: 1), class: "btn btn-danger crud" , method: :delete, data: { confirm: "Are you sure?" }%>'.replace(1,city_id);

						Object.keys(dict).forEach(function(key){
							$(key).html(dict[key]);
						})
					}
				});
			}
		});
	});

</script>


<div id="center">
	<div class="container">
		<div class="wrapper clearfix">
			<h1>List Citites</h1>
			<ul class="nav">
				<li><select class="form-control" id="country">
					<% Country.all.each do |country| %>
					<option value="<%= country.id %>"><%= country.name %></option>
					<% end %>
				</select>
			</li>
			
			<li>
				<select class="form-control" id="city">
					<% @country.cities.each do |city| %>
					<option value="<%= city.id  %>"><%= city.name %></option>
					<% end %>
				</select>
			</li>
		</ul>
	</div>
</div>
</div>

<div id="content">
	<!-- <% if !notice.nil? %>
	<p id="notice" class="alert alert-success"><%= notice %></p>
	<% end %> -->
	<%= render partial: "shared/flash_messages", flash: flash %> 

	<div class="container">
		<div class="row">
			<div class="col-xs-11 col-sm-11">
				<div class="row">
					<div class="col-xs-4 col-sm-4">
						<h2 class="text-center" style="margin: 0;">Information</h2>
						<p>
							<strong>Name:</strong>
							<span id="nameCountry"><%= @country.name %></span>
						</p>


						<p>
							<strong>Flag:</strong>
							<img src="<%= @country.url %>" width="100" height="70"/> 
							<!--<%= image_tag @country.flag, width: 100, height: 70 %>-->
						</p>
					</div>

					<div class="col-xs-8 col-sm-8">
						<h2 class="text-center" style="margin: 0;">Image</h2>

						<div id="image_cities" class="zoom-gallery">

						</div>

					</div>
				</div>
			</div>

			<div class="col-xs-1 col-sm-1">
				<h1></h1>
				<div class="crud" id="new">
				<%= link_to 'New', new_city_path, class: "btn btn-success crud" %>
				</div>
				<div class="crud" id="edit">
					<%= link_to 'Edit', edit_city_path(@country), class: "btn btn-info crud"%> 
				</div>
				<div class="crud" id="destroy">
					<%= link_to 'Destroy', city_path(id: 0),  class: "btn btn-danger crud" , method: :delete, data: { class: "form-control", confirm: 'Are you sure?' } %>
				</div>
				<div class="crud" id="back">
					<%= link_to 'Back', countries_path,  class: "btn btn-warning crud"%>
				</div>
				
			</div>

		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<script type="text/javascript">
 $(document).ready(function() {
    $('.selectpicker').selectpicker({
        style: 'btn-default',
        size: false
    });
});

</script>

app/views/layouts/_header.html.erb
<div role="navigation" class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button data-target="#navbar-content" data-toggle="collapse" class="navbar-toggle" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="fa fa-bars"></span>
        </button>
        <a href="<%= countries_path %>" class="navbar-brand">
          <img src="https://cdn4.iconfinder.com/data/icons/ios7-line/512/Earth.png">
          <span> World </span>
        </a>
      </div>


      <div class="collapse navbar-collapse navbar-right" id="navbar-content">
        <ul style="margin-right:60px;" class="nav navbar-nav">

        </ul>
        <ul class="nav navbar-nav">
          <li class="dropdown" id="fat-menu">
          </li>
        </ul>
      </div>

    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geography</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bs_flash_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>